version: "3"
services:
  jenkins:
    image: jenkins/jenkins:lts
    ports: 
      - 8090:8080
      - 50000:50000
    volumes:
      - /tmp/jenkins_home:/var/jenkins_home

  tomcat:
    image: tomcat:7.0.93-jre8
    ports:
      - 8080:8080
#    volumes:


  mysql:
    image: mysql:5.7.25
    ports:
      - 3306:3306
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=root
#      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
#      - MYSQL_RANDOM_ROOT_PASSWORD=no
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
      - MYSQL_HOST=localhost
    volumes:
      - /tmp/mysql_data:/var/lib/mysql
